Repository kubeflow/mpi-operator, pull requests merged in 2018-08, with the labels that each got.

#23 make dep sync with tf-operator to support Kubernetes 1.9
  Gopkg.lock
  Gopkg.toml
  pkg/apis/kubeflow/v1alpha1/zz_generated.deepcopy.go
  pkg/client/clientset/versioned/clientset.go
  pkg/client/clientset/versioned/fake/clientset_generated.go
  pkg/client/clientset/versioned/fake/register.go
  pkg/client/clientset/versioned/scheme/register.go
  pkg/client/clientset/versioned/typed/kubeflow/v1alpha1/fake/fake_mpijob.go
  pkg/client/informers/externalversions/factory.go
  pkg/client/informers/externalversions/generic.go
  pkg/client/informers/externalversions/internalinterfaces/factory_interfaces.go
  pkg/client/informers/externalversions/kubeflow/interface.go
  pkg/client/informers/externalversions/kubeflow/v1alpha1/interface.go
  pkg/client/informers/externalversions/kubeflow/v1alpha1/mpijob.go
  pkg/client/listers/kubeflow/v1alpha1/expansion_generated.go
  pkg/client/listers/kubeflow/v1alpha1/mpijob.go
Labels: lgtm, size/L

#24 copy labels to pod from podTemplate
  pkg/controllers/mpi_job_controller.go
Labels: size/M

#30 Add jlewi@ as an approver to unblock PRs.
  OWNERS
Labels: lgtm, size/XS

#26 launcher also needs delete gpu requests
  pkg/controllers/mpi_job_controller.go
Labels: approved, lgtm, size/XS

#34 properly set the `mpi_job_name` label
  pkg/controllers/mpi_job_controller.go
Labels: approved, lgtm, size/XS

#28 Support retry times
  pkg/apis/kubeflow/v1alpha1/types.go
  pkg/apis/kubeflow/v1alpha1/zz_generated.deepcopy.go
  pkg/controllers/mpi_job_controller.go
Labels: approved, lgtm, size/S

#33 add cheyang as reviewer
  OWNERS
Labels: approved, lgtm, size/XS

#32 update tensorflow benchmark dockerfile to latest horovod
  examples/tensorflow-benchmarks/Dockerfile
Labels: size/XS

#36 remove max_slots from hostfile to allow oversubscribing
  pkg/controllers/mpi_job_controller.go
Labels: approved, lgtm, size/XS

#35 make job launcher no resource requirement, and prefer to put in master
  pkg/apis/kubeflow/v1alpha1/types.go
  pkg/controllers/mpi_job_controller.go
Labels: approved, lgtm, size/M

#38 fix restart policy for statefulset
  pkg/controllers/mpi_job_controller.go
Labels: approved, lgtm, size/XS

#39 add imagenet example using efs
  examples/tensorflow-benchmarks-imagenet.yaml
Labels: size/M

#41 Remove pdmack from OWNERS
  OWNERS
Labels: approved, lgtm, size/XS

#44 allow the launcher job to have a `RestartPolicy` of `Never`
  pkg/controllers/mpi_job_controller.go
Labels: size/XS
