Repository kubeflow/mpi-operator, pull requests merged in 2019-05, with the labels that each got.

#98 Add v1alpha2 MPIJob controller
  .travis.yml
  cmd/mpi-operator/main.go
  pkg/controllers/v1alpha1/mpi_job_controller.go
  pkg/controllers/v1alpha1/mpi_job_controller_test.go
  pkg/controllers/v1alpha2/mpi_job_controller.go
  pkg/controllers/v1alpha2/mpi_job_controller_test.go
Labels: approved, lgtm, size/XXL

#109 Small refactor of cmd dir and fix some bugs for v1alpha2
  cmd/mpi-operator.v1alpha1/main.go
  cmd/mpi-operator.v1alpha2/app/options/options.go
  cmd/mpi-operator.v1alpha2/app/server.go
  cmd/mpi-operator.v1alpha2/main.go
  deploy/crd/crd-v1alpha1.yaml
  deploy/crd/crd-v1alpha2.yaml
  examples/v1alpha2/tensorflow-benchmarks-custom.yaml
  examples/v1alpha2/tensorflow-benchmarks-imagenet.yaml
  examples/v1alpha2/tensorflow-benchmarks.yaml
  pkg/controllers/v1alpha2/mpi_job_controller.go
  pkg/version/version.go
Labels: approved, lgtm, needs-ok-to-test, size/L

#110 Add leader election
  Gopkg.lock
  cmd/mpi-operator.v1alpha2/app/server.go
  pkg/apis/kubeflow/v1alpha2/constants.go
Labels: approved, lgtm, ok-to-test, size/L
