Repository kubeflow/mpi-operator, pull requests merged in 2019-12, with the labels that each got.

#153 ocp4_x
  deploy/mpi-operator.yaml
Labels: approved, lgtm, needs-ok-to-test, size/XS

#158 Update mpi-operator installation doc to use Kustomize
  README.md
Labels: approved, lgtm, size/S

#159 [RFC] Add initial version of the roadmap
  ROADMAP.md
Labels: size/S
