Repository kubeflow/mpi-operator, pull requests merged in 2019-09, with the labels that each got.

#136 Single_deploy
  deploy/1-namespace.yaml
  deploy/2-rbac.yaml
  deploy/3-mpi-operator.yaml
  deploy/crd/crd-v1alpha1.yaml
  deploy/crd/crd-v1alpha2.yaml
  deploy/mpi-operator.yaml
Labels: approved, lgtm, needs-ok-to-test, size/L

#142 Add default init container ResourceRequirements
  pkg/controllers/v1alpha2/mpi_job_controller.go
Labels: approved, lgtm, needs-ok-to-test, size/S

#143 Update README to use the new single deploy config
  README.md
Labels: approved, lgtm, size/XS
