Repository kubeflow/mpi-operator, pull requests merged in 2019-02, with the labels that each got.

#87 Support gang scheduling
  Gopkg.lock
  cmd/mpi-operator/main.go
  pkg/controllers/mpi_job_controller.go
  pkg/controllers/mpi_job_controller_test.go
Labels: approved, lgtm, size/L

#89 Add StartTime and CompletionTime in job status
  .gitignore
  pkg/apis/kubeflow/v1alpha1/types.go
  pkg/apis/kubeflow/v1alpha1/zz_generated.deepcopy.go
  pkg/controllers/mpi_job_controller.go
  pkg/controllers/mpi_job_controller_test.go
Labels: approved, lgtm, needs-ok-to-test, size/L

#91 Remove unnecessary minAvailableWorkerReplicas check
  pkg/controllers/mpi_job_controller.go
Labels: approved, lgtm, size/XS

#94 Added missing labels when creating configmaps
  pkg/controllers/mpi_job_controller.go
Labels: approved, lgtm, size/XS
