Repository kubeflow/mpi-operator, pull requests merged in 2019-04, with the labels that each got.

#105 Fix how to add to queue
  Gopkg.lock
  pkg/controllers/mpi_job_controller.go
Labels: approved, lgtm, needs-ok-to-test, size/S

#106 only create the pbdInformer when gang scheduling is enabled
  cmd/mpi-operator/main.go
  pkg/controllers/mpi_job_controller.go
  pkg/controllers/mpi_job_controller_test.go
Labels: approved, lgtm, needs-ok-to-test, size/M

#107 Fix some lint errors
  pkg/apis/kubeflow/v1alpha2/common_types.go
Labels: approved, lgtm, ok-to-test, size/XS
