Repository kubeflow/mpi-operator, pull requests merged in 2019-06, with the labels that each got.

#111 Switch pdb to podgroup for gang scheduling
  Gopkg.lock
  cmd/mpi-operator.v1alpha2/app/server.go
  pkg/controllers/v1alpha2/mpi_job_controller.go
Labels: approved, lgtm, size/L

#114 Add default-gen and set default through scheme
  hack/update-codegen.sh
  pkg/apis/kubeflow/v1alpha2/default.go
  pkg/apis/kubeflow/v1alpha2/doc.go
  pkg/apis/kubeflow/v1alpha2/register.go
  pkg/apis/kubeflow/v1alpha2/zz_generated.defaults.go
  pkg/controllers/v1alpha2/mpi_job_controller.go
Labels: approved, lgtm, size/L

#116 Delete launcherOnMaster field in v1alpha2
  pkg/apis/kubeflow/v1alpha2/types.go
  pkg/controllers/v1alpha2/mpi_job_controller.go
Labels: approved, lgtm, size/M

#112 When MpiJob finished, delete podgroup and set worker count to 0
  cmd/mpi-operator.v1alpha2/app/server.go
  pkg/apis/kubeflow/v1alpha2/default.go
  pkg/apis/kubeflow/v1alpha2/types.go
  pkg/controllers/v1alpha2/mpi_job_controller.go
Labels: approved, lgtm, size/L

#113 Change the launcher done status judge logic
  pkg/controllers/v1alpha1/mpi_job_controller.go
  pkg/controllers/v1alpha1/mpi_job_controller_test.go
Labels: approved, lgtm, size/S

#117 add subresources status to crd
  deploy/crd/crd-v1alpha2.yaml
Labels: approved, lgtm, size/XS

#119 init kubebatchClient before use
  pkg/controllers/v1alpha2/mpi_job_controller.go
Labels: approved, lgtm, size/XS

#120 update mpijob condition
  pkg/controllers/v1alpha2/mpi_job_controller.go
  pkg/controllers/v1alpha2/mpi_job_controller_status.go
Labels: approved, lgtm, size/L

#124 fix failed ut
  pkg/controllers/v1alpha2/mpi_job_controller.go
  pkg/controllers/v1alpha2/mpi_job_controller_test.go
Labels: approved, lgtm, size/L

#123 fix bug about gang scheduling
  cmd/mpi-operator.v1alpha2/app/server.go
  pkg/controllers/v1alpha2/mpi_job_controller.go
  pkg/controllers/v1alpha2/mpi_job_controller_test.go
Labels: approved, lgtm, size/M

#125 update dockerfile
  Dockerfile
Labels: approved, lgtm, size/S

#126 update mpijob status accord according to job condition
  pkg/controllers/v1alpha2/mpi_job_controller.go
Labels: approved, lgtm, size/M
