Repository kubeflow/mpi-operator, pull requests merged in 2019-03, with the labels that each got.

#96 Refactor label map and launcherName
  pkg/controllers/mpi_job_controller.go
Labels: approved, lgtm, needs-ok-to-test, size/M

#97 adding poddisruptionbudgets rbac rules
  deploy/2-rbac.yaml
Labels: approved, lgtm, needs-ok-to-test, size/XS

#99 Add create and update verbs to pdb
  deploy/2-rbac.yaml
Labels: approved, lgtm, size/XS

#100 Use kube-batch as scheduler by default when gang-scheduling is enabled
  Gopkg.lock
  Gopkg.toml
  pkg/controllers/mpi_job_controller.go
  pkg/controllers/mpi_job_controller_test.go
Labels: approved, lgtm, needs-ok-to-test, size/L

#102 add developer's guide first version
  developer_guide.md
Labels: approved, lgtm, needs-ok-to-test, size/M
