Repository kubeflow/mpi-operator, pull requests merged in 2019-01, with the labels that each got.

#64 glog uses -alsologtostderr
  deploy/3-mpi-operator.yaml
Labels: approved, lgtm, needs-ok-to-test, size/XS

#60 Allow users to specify namespace for Kubernetes informers
  cmd/mpi-operator/main.go
Labels: approved, lgtm, needs-ok-to-test, size/S

#65 Added resource kind for more informative message in MessageResourceExists
  pkg/controllers/mpi_job_controller.go
Labels: approved, lgtm, needs-ok-to-test, size/S

#68 Revamp get started doc on README.md
  README.md
Labels: approved, lgtm, needs-ok-to-test, size/L

#70 add Nivedita as reviewer
  OWNERS
Labels: approved, size/XS

#69 Remove unused getWorkerReplicas() function
  pkg/controllers/mpi_job_controller.go
Labels: approved, lgtm, needs-ok-to-test, size/S

#62 Clarify that gpusPerNode will be ignored if this is set in pod spec
  cmd/mpi-operator/main.go
Labels: approved, lgtm, needs-ok-to-test, size/XS

#71 fix tensorflow benchmarks dockerfile
  examples/tensorflow-benchmarks/Dockerfile
Labels: approved, size/XS

#73 temporary fix of Horovod docker image
  examples/tensorflow-benchmarks/Dockerfile
Labels: size/XS

#74 Minor edits based on feedback from kubeflow/website
  README.md
Labels: approved, lgtm, needs-ok-to-test, size/XS

#76 add terrytangyuan as reviewer; remove inactive reviewers
  OWNERS
Labels: size/XS

#78 update dependencies
  Gopkg.lock
  Gopkg.toml
  pkg/apis/kubeflow/v1alpha1/zz_generated.deepcopy.go
  pkg/client/clientset/versioned/clientset.go
  pkg/client/clientset/versioned/doc.go
  pkg/client/clientset/versioned/fake/clientset_generated.go
  pkg/client/clientset/versioned/fake/doc.go
  pkg/client/clientset/versioned/fake/register.go
  pkg/client/clientset/versioned/scheme/doc.go
  pkg/client/clientset/versioned/scheme/register.go
  pkg/client/clientset/versioned/typed/kubeflow/v1alpha1/doc.go
  pkg/client/clientset/versioned/typed/kubeflow/v1alpha1/fake/doc.go
  pkg/client/clientset/versioned/typed/kubeflow/v1alpha1/fake/fake_kubeflow_client.go
  pkg/client/clientset/versioned/typed/kubeflow/v1alpha1/fake/fake_mpijob.go
  pkg/client/clientset/versioned/typed/kubeflow/v1alpha1/generated_expansion.go
  pkg/client/clientset/versioned/typed/kubeflow/v1alpha1/kubeflow_client.go
  pkg/client/clientset/versioned/typed/kubeflow/v1alpha1/mpijob.go
  pkg/client/informers/externalversions/factory.go
  pkg/client/informers/externalversions/generic.go
  pkg/client/informers/externalversions/internalinterfaces/factory_interfaces.go
  pkg/client/informers/externalversions/kubeflow/interface.go
  pkg/client/informers/externalversions/kubeflow/v1alpha1/interface.go
  pkg/client/informers/externalversions/kubeflow/v1alpha1/mpijob.go
  pkg/client/listers/kubeflow/v1alpha1/expansion_generated.go
  pkg/client/listers/kubeflow/v1alpha1/mpijob.go
Labels: approved, size/XL

#79 Switched to use NewSharedInformerFactoryWithOptions for informers
  cmd/mpi-operator/main.go
Labels: approved, lgtm, needs-ok-to-test, size/XS

#81 Support ActiveDeadlineSeconds that takes precedence over BackoffLimit
  pkg/apis/kubeflow/v1alpha1/types.go
  pkg/apis/kubeflow/v1alpha1/zz_generated.deepcopy.go
  pkg/controllers/mpi_job_controller.go
Labels: approved, lgtm, size/S

#75 Support processing resource types other than GPU
  cmd/mpi-operator/main.go
  deploy/0-crd.yaml
  pkg/apis/kubeflow/v1alpha1/types.go
  pkg/apis/kubeflow/v1alpha1/zz_generated.deepcopy.go
  pkg/controllers/mpi_job_controller.go
  pkg/controllers/mpi_job_controller_test.go
Labels: approved, lgtm, needs-ok-to-test, size/L

#83 Update kubectl version in kubectl-delivery
  cmd/kubectl-delivery/Dockerfile
Labels: approved, lgtm, size/XS

#84 update versions of k8s, go, alpine, dep
  .travis.yml
  Dockerfile
  Gopkg.lock
  Gopkg.toml
  cmd/kubectl-delivery/Dockerfile
Labels: approved, lgtm, size/M

#85 Move processing unit specific flags to MPIJobSpec
  cmd/mpi-operator/main.go
  deploy/0-crd.yaml
  pkg/apis/kubeflow/v1alpha1/types.go
  pkg/apis/kubeflow/v1alpha1/zz_generated.deepcopy.go
  pkg/controllers/mpi_job_controller.go
Labels: approved, lgtm, size/M
