Repository kubeflow/mpi-operator, pull requests merged in 2019-07, with the labels that each got.

#129 fix: Remove the hard coded kind and check version
  pkg/controllers/v1alpha2/mpi_job_controller.go
Labels: size/S

#128 fix: Fix the env log
  cmd/mpi-operator.v1alpha2/app/server.go
Labels: size/XS

#122 MXNet distributed training
  examples/mxnet/Dockerfile
  examples/mxnet/mxnet-mnist.yaml
  examples/mxnet/mxnet_mnist.py
Labels: ok-to-test, size/L

#130 update dockerfile and examples to v1alpha2
  Dockerfile
  README.md
  cmd/kubectl-delivery/Dockerfile
  cmd/mpi-operator.v1alpha2/app/options/options.go
  deploy/2-rbac.yaml
  deploy/3-mpi-operator.yaml
  examples/tensorflow-benchmarks/Dockerfile
  examples/v1alpha1/tensorflow-benchmarks-custom.yaml
  examples/v1alpha1/tensorflow-benchmarks-imagenet.yaml
  examples/v1alpha1/tensorflow-benchmarks.yaml
  examples/v1alpha2/tensorflow-benchmarks-custom.yaml
  examples/v1alpha2/tensorflow-benchmarks-imagenet.yaml
  examples/v1alpha2/tensorflow-benchmarks.yaml
Labels: approved, lgtm, size/L
