Repository kubeflow/mpi-operator, pull requests merged in 2020-01, with the labels that each got.

#163 Update README.md
  README.md
Labels: approved, lgtm, ok-to-test, size/S

#164 Update codegen to fix Travis CI
  pkg/apis/kubeflow/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/kubeflow/v1alpha2/zz_generated.deepcopy.go
  pkg/apis/kubeflow/v1alpha2/zz_generated.defaults.go
  pkg/client/clientset/versioned/clientset.go
  pkg/client/clientset/versioned/doc.go
  pkg/client/clientset/versioned/fake/clientset_generated.go
  pkg/client/clientset/versioned/fake/doc.go
  pkg/client/clientset/versioned/fake/register.go
  pkg/client/clientset/versioned/scheme/doc.go
  pkg/client/clientset/versioned/scheme/register.go
  pkg/client/clientset/versioned/typed/kubeflow/v1alpha1/doc.go
  pkg/client/clientset/versioned/typed/kubeflow/v1alpha1/fake/doc.go
  pkg/client/clientset/versioned/typed/kubeflow/v1alpha1/fake/fake_kubeflow_client.go
  pkg/client/clientset/versioned/typed/kubeflow/v1alpha1/fake/fake_mpijob.go
  pkg/client/clientset/versioned/typed/kubeflow/v1alpha1/generated_expansion.go
  pkg/client/clientset/versioned/typed/kubeflow/v1alpha1/kubeflow_client.go
  pkg/client/clientset/versioned/typed/kubeflow/v1alpha1/mpijob.go
  pkg/client/clientset/versioned/typed/kubeflow/v1alpha2/doc.go
  pkg/client/clientset/versioned/typed/kubeflow/v1alpha2/fake/doc.go
  pkg/client/clientset/versioned/typed/kubeflow/v1alpha2/fake/fake_kubeflow_client.go
  pkg/client/clientset/versioned/typed/kubeflow/v1alpha2/fake/fake_mpijob.go
  pkg/client/clientset/versioned/typed/kubeflow/v1alpha2/generated_expansion.go
  pkg/client/clientset/versioned/typed/kubeflow/v1alpha2/kubeflow_client.go
  pkg/client/clientset/versioned/typed/kubeflow/v1alpha2/mpijob.go
  pkg/client/informers/externalversions/factory.go
  pkg/client/informers/externalversions/generic.go
  pkg/client/informers/externalversions/internalinterfaces/factory_interfaces.go
  pkg/client/informers/externalversions/kubeflow/interface.go
  pkg/client/informers/externalversions/kubeflow/v1alpha1/interface.go
  pkg/client/informers/externalversions/kubeflow/v1alpha1/mpijob.go
  pkg/client/informers/externalversions/kubeflow/v1alpha2/interface.go
  pkg/client/informers/externalversions/kubeflow/v1alpha2/mpijob.go
  pkg/client/listers/kubeflow/v1alpha1/expansion_generated.go
  pkg/client/listers/kubeflow/v1alpha1/mpijob.go
  pkg/client/listers/kubeflow/v1alpha2/expansion_generated.go
  pkg/client/listers/kubeflow/v1alpha2/mpijob.go
Labels: approved, lgtm, size/M

#166 Revamp contributing guide
  CONTRIBUTING.md
  developer_guide.md
Labels: approved, lgtm, size/M

#167 Adding helm chart
  hack/helm/mpi-operator/Chart.yaml
  hack/helm/mpi-operator/README.md
  hack/helm/mpi-operator/templates/_helpers.tpl
  hack/helm/mpi-operator/templates/mpi-operator-clusterrole.yaml
  hack/helm/mpi-operator/templates/mpi-operator-deployment.yaml
  hack/helm/mpi-operator/templates/mpi-operator-rolebinding.yaml
  hack/helm/mpi-operator/templates/mpi-operator-serviceaccount.yaml
  hack/helm/mpi-operator/templates/mpijob-crd.yaml
  hack/helm/mpi-operator/values.yaml
Labels: approved, lgtm, needs-ok-to-test, size/L

#168 Fixes #165: Switch to use golangci-lint
  .travis.yml
  linter_config.json
  pkg/controllers/v1alpha1/mpi_job_controller_test.go
  pkg/controllers/v1alpha2/mpi_job_controller_test.go
Labels: approved, lgtm, size/L

#170 Use explicit path to vendor folder to fix Travis build
  .travis.yml
Labels: size/XS

#172 Add default ephemeral storage for init container
  pkg/controllers/v1alpha2/mpi_job_controller.go
Labels: approved, lgtm, size/M

#171 Overwrite NVIDIA env vars to avoid using GPUs on launcher
  pkg/controllers/v1alpha2/mpi_job_controller.go
Labels: approved, lgtm, size/S

#173 Add callbacks around additional leader election phases
  cmd/mpi-operator.v1alpha2/app/server.go
Labels: approved, lgtm, size/S

#176 Update instruction on lint check and dependency management
  CONTRIBUTING.md
Labels: approved, lgtm, size/XS

#177 Add health check for leader election
  cmd/mpi-operator.v1alpha2/app/server.go
  go.mod
  vendor/k8s.io/apiserver/pkg/server/healthz/doc.go
  vendor/k8s.io/apiserver/pkg/server/healthz/healthz.go
  vendor/modules.txt
Labels: approved, lgtm, size/L

#175 Honor user-typed worker command
  pkg/controllers/v1alpha2/mpi_job_controller.go
Labels: approved, lgtm, size/XS

#174 Expose main container name as a configurable field
  pkg/apis/kubeflow/v1alpha2/types.go
  pkg/controllers/v1alpha2/mpi_job_controller.go
Labels: approved, size/S

#178 Add RunPolicy to MPIJobSpec that reuses kubeflow/common spec
  hack/update-codegen.sh
  pkg/apis/kubeflow/v1alpha2/types.go
  pkg/apis/kubeflow/v1alpha2/zz_generated.deepcopy.go
  pkg/client/clientset/versioned/clientset.go
  pkg/client/clientset/versioned/fake/clientset_generated.go
  pkg/controllers/v1alpha2/mpi_job_controller.go
Labels: approved, lgtm, size/M

#179 Add initial list of adopters
  ADOPTERS.md
  README.md
Labels: approved, lgtm, size/S

#180 Add Polyaxon to list of adopters
  ADOPTERS.md
Labels: approved, lgtm, needs-ok-to-test, size/XS
