Repository kubeflow/mpi-operator, pull requests merged in 2020-04, with the labels that each got.

#210 add an example for cpu-only case
  examples/hovorod-cpu/Dockerfile.cpu
  examples/hovorod-cpu/README.md
  examples/hovorod-cpu/tensorflow-mnist.yaml
  examples/hovorod-cpu/tensorflow_mnist.py
Labels: approved, lgtm, needs-ok-to-test, size/L

#212 add carmark as reviewer
  OWNERS
Labels: approved, lgtm, size/XS

#216 add Qutoutiao as an adopter
  ADOPTERS.md
Labels: needs-ok-to-test, size/XS

#215 add monitor metrics
  cmd/mpi-operator.v1alpha2/app/options/options.go
  cmd/mpi-operator.v1alpha2/app/server.go
  cmd/mpi-operator.v1alpha2/main.go
  go.mod
  go.sum
  pkg/controllers/v1alpha2/mpi_job_controller.go
Labels: approved, lgtm, needs-ok-to-test, size/M

#220 Update dev guide to remove the mention of vendor directories
  CONTRIBUTING.md
Labels: approved, lgtm, size/XS

#222 Dynamically grabbing the version of code-generator
  hack/update-codegen.sh
Labels: approved, lgtm, size/XS

#221 Remove BackoffLimit and ActiveDeadlineSeconds from MPIJobSpec
  pkg/apis/kubeflow/v1/default.go
  pkg/apis/kubeflow/v1/openapi_generated.go
  pkg/apis/kubeflow/v1/types.go
  pkg/apis/kubeflow/v1/zz_generated.deepcopy.go
  pkg/controllers/v1/mpi_job_controller.go
Labels: approved, lgtm, size/M

#237 rename hovorod to horovod
  examples/horovod/Dockerfile.cpu
  examples/horovod/README.md
  examples/horovod/tensorflow-mnist.yaml
  examples/horovod/tensorflow_mnist.py
Labels: approved, lgtm, needs-ok-to-test, size/XS

#238 Add defaults for backOffLimit and activeDeadlineSeconds
  pkg/controllers/v1/mpi_job_controller.go
Labels: approved, lgtm, size/S

#239 Suppress redundant echoed output in Makefile
  Makefile
Labels: lgtm, size/XS

#241 Remove worker command
  examples/horovod/tensorflow-mnist.yaml
Labels: approved, lgtm, ok-to-test, size/XS

#242 use volcano scheduler
  cmd/mpi-operator.v1/app/server.go
  go.mod
  go.sum
  pkg/apis/kubeflow/v1/openapi_generated.go
  pkg/apis/kubeflow/v1alpha2/openapi_generated.go
  pkg/controllers/v1/mpi_job_controller.go
  pkg/controllers/v1/mpi_job_controller_test.go
Labels: approved, lgtm, size/XXL
