Repository kubeflow/mpi-operator, pull requests merged in 2020-12, with the labels that each got.

#300 Support setting queue name
  pkg/controllers/v1/mpi_job_controller.go
Labels: approved, lgtm, size/XS

#302 Go fmt changes that caused the git tree to be dirty
  pkg/apis/kubeflow/v1alpha2/types.go
  pkg/controllers/v1alpha2/mpi_job_controller.go
Labels: approved, lgtm, size/XS

#303 Cleans up the unused go.sum dependencies
  go.sum
Labels: approved, lgtm, size/XS

#305 Migrate to GitHub Pipelines from travis
  .github/workflows/golangci-lint.yml
  .github/workflows/main.yml
  .gitignore
  .travis.yml
  Makefile
  README.md
  go.mod
  go.sum
Labels: approved, size/M

#308 Fixed golangci lint issue
  .gitignore
  pkg/controllers/v1alpha2/mpi_job_controller.go
Labels: approved, lgtm, size/XS

#309 Add link to GitHub Actions builds on master branch
  README.md
Labels: approved, lgtm, size/XS

#311 Implemented codeql for code scanning
  .github/workflows/codeql.yml
Labels: approved, lgtm, size/M

#313 fix: non-running worker will not be removed under CleanPodPolicyRunning
  pkg/controllers/v1/mpi_job_controller.go
Labels: approved, lgtm, size/S
