Repository kubeflow/mpi-operator, pull requests merged in 2020-06, with the labels that each got.

#264 Add nodeSelector and tolerations in Helm Charts
  hack/helm/mpi-operator/templates/mpi-operator-deployment.yaml
  hack/helm/mpi-operator/values.yaml
Labels: approved, lgtm, needs-ok-to-test, size/S

#267 fix volcano scheduler rbac
  deploy/v1/mpi-operator.yaml
Labels: approved, lgtm, size/XS

#271 Update mpi_job_controller.go
  pkg/controllers/v1/mpi_job_controller.go
Labels: approved, lgtm, needs-ok-to-test, size/XS

#272 Prune OWNERS file
  OWNERS
Labels: approved, lgtm, size/XS

#273 Rename Ant Financial to Ant Group
  ADOPTERS.md
Labels: approved, lgtm, size/XS

#275 Avoid potential nil pointer.
  pkg/controllers/v1/mpi_job_controller.go
  pkg/controllers/v1alpha2/mpi_job_controller.go
Labels: approved, lgtm, ok-to-test, size/M
