Repository kubeflow/mpi-operator, pull requests merged in 2020-02, with the labels that each got.

#181 Some edits on README.md based on website feedback
  README.md
Labels: approved, lgtm, size/S

#182 add nvidia as adopter
  ADOPTERS.md
Labels: approved, lgtm, size/XS

#183 add tencent as an adopter
  ADOPTERS.md
Labels: lgtm, size/XS

#184 Correct capitalization for Caicloud
  ADOPTERS.md
Labels: lgtm, size/XS

#161 update kustomize deploy command
  README.md
Labels: approved, lgtm, needs-ok-to-test, size/XS

#185 Add note on the use of kubectl kustomize
  README.md
Labels: approved, lgtm, size/S

#186 Use operator's namespace for initializing informers and endpoints/leaderElection
  cmd/mpi-operator.v1alpha2/app/server.go
Labels: approved, lgtm, size/S

#188 add scheduling groups of kube-batch/volcano for role
  deploy/mpi-operator.yaml
Labels: approved, lgtm, size/XS

#190 Add error log when pod spec does not have any containers
  pkg/controllers/v1alpha2/mpi_job_controller.go
Labels: approved, lgtm, size/XS

#193 Changed to Distroless image
  Dockerfile
Labels: approved, lgtm, size/S
