Repository kubeflow/mpi-operator, pull requests merged in 2020-05, with the labels that each got.

#243 Add licenses used by the dependencies
  Dockerfile
  third_party/library/license.txt
  third_party_licenses/additional_license_info.csv
  third_party_licenses/dep.txt
  third_party_licenses/dep_repo.manual.csv
  third_party_licenses/license_info.csv
  third_party_licenses/repo.txt
Labels: approved, lgtm, size/XXL

#203 Convert launcher job and statefulset worker to pod
  Dockerfile
  cmd/mpi-operator.v1/app/server.go
  deploy/v1/mpi-operator.yaml
  deploy/v1alpha2/mpi-operator.yaml
  pkg/apis/kubeflow/v1/constants.go
  pkg/apis/kubeflow/v1/default.go
  pkg/controllers/v1/mpi_job_controller.go
  pkg/controllers/v1/mpi_job_controller_status.go
  pkg/controllers/v1/mpi_job_controller_test.go
Labels: approved, lgtm, size/XL

#245 Fix wrong create path in README's installation instruction
  README.md
Labels: approved, lgtm, needs-ok-to-test, size/XS

#246 Move from glog to klog
  cmd/kubectl-delivery/app/server.go
  cmd/kubectl-delivery/main.go
  cmd/mpi-operator.v1/app/server.go
  cmd/mpi-operator.v1/main.go
  cmd/mpi-operator.v1alpha1/main.go
  cmd/mpi-operator.v1alpha2/app/server.go
  cmd/mpi-operator.v1alpha2/main.go
  go.mod
  pkg/controllers/kubectl_delivery/controller.go
  pkg/controllers/v1/mpi_job_controller.go
  pkg/controllers/v1alpha1/mpi_job_controller.go
  pkg/controllers/v1alpha2/mpi_job_controller.go
Labels: approved, lgtm, ok-to-test, size/L

#249 Fix the wrong build image path in Dockerfile
  Dockerfile
Labels: approved, lgtm, ok-to-test, size/XS

#251 fix dockerfile copy path
  Dockerfile
Labels: approved, lgtm, size/XS

#252 Consistent label conventions with other operators
  pkg/controllers/v1/mpi_job_controller.go
Labels: approved, lgtm, size/XS

#253 Add code formatting check
  Makefile
  cmd/kubectl-delivery/app/server.go
  cmd/mpi-operator.v1/app/server.go
  cmd/mpi-operator.v1alpha2/app/server.go
  pkg/controllers/kubectl_delivery/controller.go
  pkg/controllers/v1/mpi_job_controller.go
  pkg/controllers/v1alpha1/mpi_job_controller.go
Labels: approved, lgtm, size/S

#255 Add Docker pulls stats badge
  README.md
Labels: approved, lgtm, size/XS

#256 switch back to alpine for kubectl delivery
  cmd/kubectl-delivery/Dockerfile
Labels: approved, lgtm, size/XS

#257 Fix issue in v1 controller's CRD existence check
  cmd/mpi-operator.v1/app/server.go
Labels: approved, lgtm, size/XS

#258 Update ADOPTERS.md
  ADOPTERS.md
Labels: approved, lgtm, needs-ok-to-test, size/XS

#259 Add release notes
  RELEASE.md
Labels: approved, lgtm, size/M
