Repository kubeflow/mpi-operator, pull requests merged in 2020-03, with the labels that each got.

#199 Fixed typo "Pingduoduo" in ADOPTERS.md
  ADOPTERS.md
Labels: approved, lgtm, ok-to-test, size/XS

#200 add priorityClassName for PodGroup
  pkg/controllers/v1alpha2/mpi_job_controller.go
Labels: approved, lgtm, size/S

#196 refactoring the kubectl-delivery to improve the launcher performance
  .travis.yml
  cmd/kubectl-delivery/Dockerfile
  cmd/kubectl-delivery/app/options/options.go
  cmd/kubectl-delivery/app/server.go
  cmd/kubectl-delivery/deliver_kubectl.sh
  cmd/kubectl-delivery/main.go
  deploy/mpi-operator.yaml
  go.mod
  pkg/controllers/kubectl_delivery/controller.go
  pkg/controllers/kubectl_delivery/controller_test.go
  pkg/controllers/kubectl_delivery/utils_test.go
  pkg/controllers/v1alpha2/mpi_job_controller.go
Labels: approved, lgtm, size/XL

#204 Add to Adopters Mellanox Technologies
  ADOPTERS.md
Labels: approved, lgtm, needs-ok-to-test, size/XS

#205 fix namespace issue
  cmd/mpi-operator.v1alpha2/app/options/options.go
  cmd/mpi-operator.v1alpha2/app/server.go
Labels: approved, lgtm, size/S

#207 Add link to blog post
  README.md
Labels: approved, lgtm, size/XS

#209 add Makefile
  .gitignore
  .travis.yml
  Makefile
  pkg/version/version.go
Labels: approved, lgtm, size/M
