Repository kubeflow/mpi-operator, pull requests merged in 2021-03, with the labels that each got.

#326 MPI Operator: Move manifests development upstream
  README.md
  manifests/mpi-operator/base/cluster-role-binding.yaml
  manifests/mpi-operator/base/cluster-role.yaml
  manifests/mpi-operator/base/crd.yaml
  manifests/mpi-operator/base/deployment.yaml
  manifests/mpi-operator/base/kustomization.yaml
  manifests/mpi-operator/base/params.env
  manifests/mpi-operator/base/service-account.yaml
  manifests/mpi-operator/overlays/application/application.yaml
  manifests/mpi-operator/overlays/application/kustomization.yaml
Labels: approved, lgtm, size/L

#332 add support for elastic horovod on v1
  examples/horovod/tensorflow-mnist-elastic.yaml
  pkg/controllers/v1/mpi_job_controller.go
  pkg/controllers/v1/mpi_job_controller_test.go
Labels: lgtm, size/L

#331 Remove launcherRunsWorkload flag
  cmd/mpi-operator.v1/app/options/options.go
  cmd/mpi-operator.v1/app/server.go
  pkg/controllers/v1/mpi_job_controller.go
  pkg/controllers/v1/mpi_job_controller_test.go
Labels: lgtm, size/S

#334 fix role updating issue
  examples/horovod/tensorflow-mnist-elastic.yaml
  pkg/controllers/v1/mpi_job_controller.go
  pkg/controllers/v1/mpi_job_controller_test.go
Labels: approved, lgtm, size/M

#338 fix --min-np and --max-np args in elastic example
  examples/horovod/tensorflow-mnist-elastic.yaml
Labels: approved, lgtm, size/XS

#335 propose elastic training with horovod with mpi-operator
  proposals/diagrams/elastic-horovod-overall.png
  proposals/elastic-horovod.md
Labels: approved, lgtm, size/M
