Repository kubeflow/mpi-operator, pull requests merged in 2021-06, with the labels that each got.

#360 Propose a new architecture with focus on scalability and robustness
  proposals/scalable-robust-operator.md
Labels: approved, lgtm, size/L

#366 Fork v2 controller and API in a new module
  Dockerfile.v2
  hack/update-codegen.sh
  v2/Makefile
  v2/cmd/mpi-operator/app/options/options.go
  v2/cmd/mpi-operator/app/server.go
  v2/cmd/mpi-operator/main.go
  v2/go.mod
  v2/go.sum
  v2/pkg/apis/kubeflow/v2/constants.go
  v2/pkg/apis/kubeflow/v2/default.go
  v2/pkg/apis/kubeflow/v2/doc.go
  v2/pkg/apis/kubeflow/v2/openapi_generated.go
  v2/pkg/apis/kubeflow/v2/register.go
  v2/pkg/apis/kubeflow/v2/swagger.json
  v2/pkg/apis/kubeflow/v2/types.go
  v2/pkg/apis/kubeflow/v2/zz_generated.deepcopy.go
  v2/pkg/apis/kubeflow/v2/zz_generated.defaults.go
  v2/pkg/client/clientset/versioned/clientset.go
  v2/pkg/client/clientset/versioned/doc.go
  v2/pkg/client/clientset/versioned/fake/clientset_generated.go
  v2/pkg/client/clientset/versioned/fake/doc.go
  v2/pkg/client/clientset/versioned/fake/register.go
  v2/pkg/client/clientset/versioned/scheme/doc.go
  v2/pkg/client/clientset/versioned/scheme/register.go
  v2/pkg/client/clientset/versioned/typed/kubeflow/v2/doc.go
  v2/pkg/client/clientset/versioned/typed/kubeflow/v2/fake/doc.go
  v2/pkg/client/clientset/versioned/typed/kubeflow/v2/fake/fake_kubeflow_client.go
  v2/pkg/client/clientset/versioned/typed/kubeflow/v2/fake/fake_mpijob.go
  v2/pkg/client/clientset/versioned/typed/kubeflow/v2/generated_expansion.go
  v2/pkg/client/clientset/versioned/typed/kubeflow/v2/kubeflow_client.go
  v2/pkg/client/clientset/versioned/typed/kubeflow/v2/mpijob.go
  v2/pkg/client/informers/externalversions/factory.go
  v2/pkg/client/informers/externalversions/generic.go
  v2/pkg/client/informers/externalversions/internalinterfaces/factory_interfaces.go
  v2/pkg/client/informers/externalversions/kubeflow/interface.go
  v2/pkg/client/informers/externalversions/kubeflow/v2/interface.go
  v2/pkg/client/informers/externalversions/kubeflow/v2/mpijob.go
  v2/pkg/client/listers/kubeflow/v2/expansion_generated.go
  v2/pkg/client/listers/kubeflow/v2/mpijob.go
  v2/pkg/controller/mpi_job_controller.go
  v2/pkg/controller/mpi_job_controller_status.go
  v2/pkg/controller/mpi_job_controller_test.go
  v2/pkg/version/version.go
Labels: approved, lgtm, size/XXL

#368 Fix kubectl-delivery security issues
  cmd/kubectl-delivery/app/server.go
Labels: approved, lgtm, size/XS

#369 Merge v2 Makefile into main one
  .github/workflows/codeql.yml
  .github/workflows/main.yml
  Dockerfile
  Dockerfile.v2
  Makefile
  go.sum
  v2/Makefile
Labels: approved, lgtm, size/L

#370 Upgrade v2 dependencies to k8s 1.19
  v2/cmd/mpi-operator/app/server.go
  v2/go.mod
  v2/go.sum
  v2/pkg/client/clientset/versioned/clientset.go
  v2/pkg/client/clientset/versioned/fake/register.go
  v2/pkg/client/clientset/versioned/typed/kubeflow/v2/fake/fake_mpijob.go
  v2/pkg/client/clientset/versioned/typed/kubeflow/v2/mpijob.go
  v2/pkg/client/informers/externalversions/kubeflow/v2/mpijob.go
  v2/pkg/client/listers/kubeflow/v2/mpijob.go
  v2/pkg/controller/mpi_job_controller.go
Labels: approved, lgtm, size/XL

#371 kubectl-delivery wait all workers to become readiness
  pkg/controllers/kubectl_delivery/controller.go
  pkg/controllers/kubectl_delivery/controller_test.go
Labels: approved, lgtm, size/M
