Repository kubeflow/mpi-operator, pull requests merged in 2021-07, with the labels that each got.

#375 Add integration tests for v2 controller
  Makefile
  examples/horovod/Dockerfile
  examples/horovod/README.md
  examples/horovod/tensorflow-mnist.yaml
  manifests/base/cluster-role.yaml
  manifests/base/crd.yaml
  manifests/base/deployment.yaml
  manifests/base/kustomization.yaml
  manifests/base/params.env
  manifests/overlays/dev/kustomization.yaml
  v2/cmd/mpi-operator/app/options/options.go
  v2/cmd/mpi-operator/app/server.go
  v2/go.mod
  v2/go.sum
  v2/pkg/controller/mpi_job_controller.go
  v2/pkg/controller/mpi_job_controller_test.go
  v2/test/integration/main_test.go
  v2/test/integration/mpi_job_controller_test.go
Labels: approved, lgtm, size/XXL

#374 Revert horovod example to v1
  examples/horovod/tensorflow-mnist.yaml
Labels: approved, lgtm, size/XS

#376 Consolidate validation and defaulting logic
  v2/pkg/apis/kubeflow/v2/default.go
  v2/pkg/apis/kubeflow/v2/default_test.go
  v2/pkg/apis/kubeflow/validation/validation.go
  v2/pkg/apis/kubeflow/validation/validation_test.go
  v2/pkg/controller/mpi_job_controller.go
  v2/test/integration/doc.go
Labels: approved, lgtm, size/L

#377 Remove go report card badge
  README.md
Labels: lgtm, size/XS

#380 build: Remove code coverage report
  .github/workflows/main.yml
Labels: size/XS

#382 fix comment typo related to statefulset
  pkg/controllers/v1/mpi_job_controller.go
Labels: approved, lgtm, size/XS

#379 Upgrade to apiextensions.k8s.io/v1
  manifests/base/crd.yaml
  v2/pkg/apis/kubeflow/v2beta1/types.go
  v2/pkg/apis/kubeflow/v2beta1/zz_generated.deepcopy.go
  v2/pkg/apis/kubeflow/validation/validation.go
  v2/pkg/apis/kubeflow/validation/validation_test.go
  v2/pkg/controller/mpi_job_controller.go
  v2/pkg/controller/mpi_job_controller_status.go
  v2/pkg/controller/mpi_job_controller_test.go
Labels: approved, lgtm, size/L

#385 Validate that MPIJob produces valid hostnames
  v2/pkg/apis/kubeflow/validation/validation.go
  v2/pkg/apis/kubeflow/validation/validation_test.go
Labels: approved, lgtm, size/M

#383 Allow running MPI applications as non-root
  examples/pi/Dockerfile
  examples/pi/README.md
  examples/pi/pi.cc
  examples/pi/pi.yaml
  examples/pi/sshd_config
  manifests/base/crd.yaml
  v2/cmd/mpi-operator/app/options/options.go
  v2/cmd/mpi-operator/app/server.go
  v2/pkg/apis/kubeflow/v2beta1/default.go
  v2/pkg/apis/kubeflow/v2beta1/default_test.go
  v2/pkg/apis/kubeflow/v2beta1/types.go
  v2/pkg/apis/kubeflow/validation/validation.go
  v2/pkg/apis/kubeflow/validation/validation_test.go
  v2/pkg/controller/mpi_job_controller.go
  v2/pkg/controller/mpi_job_controller_test.go
  v2/test/integration/mpi_job_controller_test.go
Labels: approved, lgtm, size/XL

#387 Fix validation tests and account for invalid cleanPodPolicy
  v2/pkg/apis/kubeflow/validation/validation_test.go
Labels: lgtm, size/S

#390 Optimize OpenMPI image size
  examples/pi/Dockerfile
Labels: lgtm, size/S
