Repository kubeflow/mpi-operator, pull requests merged in 2021-04, with the labels that each got.

#345 feat: upgrade common & volcano version
  cmd/mpi-operator.v1/app/server.go
  go.mod
  go.sum
  pkg/controllers/v1/mpi_job_controller.go
  pkg/controllers/v1/mpi_job_controller_test.go
Labels: approved, lgtm, size/L

#346 chore: Remove inactive owners
  OWNERS
Labels: approved, lgtm, size/XS

#347 Add mpi job info metric
  pkg/controllers/v1/mpi_job_controller.go
Labels: approved, lgtm, size/XS

#350 Update metrics doc
  README.md
Labels: approved, lgtm, size/S

#353 fix trimleft issue when deleting redundant pods
  pkg/controllers/v1/mpi_job_controller.go
Labels: approved, lgtm, size/XS

#349 Fix typo
  proposals/elastic-horovod.md
Labels: approved, lgtm, size/XS

#355 chore: Add Wang Zhang as a reviewer
  OWNERS
Labels: approved, lgtm, size/XS
