Repository kubeflow/mpi-operator, pull requests merged in 2021-08, with the labels that each got.

#397 Fix Discovery script for intel
  v2/pkg/controller/mpi_job_controller.go
Labels: approved, lgtm, size/XS

#391 Manage launcher through k8s Job
  manifests/base/crd.yaml
  v2/cmd/mpi-operator/app/server.go
  v2/pkg/apis/kubeflow/validation/validation.go
  v2/pkg/apis/kubeflow/validation/validation_test.go
  v2/pkg/controller/mpi_job_controller.go
  v2/pkg/controller/mpi_job_controller_test.go
  v2/test/integration/mpi_job_controller_test.go
Labels: approved, lgtm, size/XL

#392 Pass runPolicy fields to the launcher Job
  examples/pi/pi-intel.yaml
  examples/pi/pi.yaml
  manifests/base/crd.yaml
  v2/pkg/apis/kubeflow/v2beta1/default.go
  v2/pkg/apis/kubeflow/v2beta1/default_test.go
  v2/pkg/apis/kubeflow/v2beta1/types.go
  v2/pkg/apis/kubeflow/v2beta1/zz_generated.deepcopy.go
  v2/pkg/apis/kubeflow/validation/validation.go
  v2/pkg/apis/kubeflow/validation/validation_test.go
  v2/pkg/controller/mpi_job_controller.go
  v2/pkg/controller/mpi_job_controller_test.go
  v2/test/integration/mpi_job_controller_test.go
Labels: approved, lgtm, size/L

#399 E2E test for v2 controller
  .github/workflows/main.yml
  Makefile
  examples/pi/pi-intel.yaml
  examples/pi/pi.cc
  examples/pi/pi.yaml
  manifests/base/deployment.yaml
  manifests/overlays/dev/.gitignore
  manifests/overlays/dev/kustomization.yaml.template
  v2/go.mod
  v2/test/e2e/e2e_suite_test.go
  v2/test/e2e/mpi_job_test.go
Labels: approved, lgtm, size/L

#403 Add E2E tests for failure, root and Intel
  Makefile
  v2/test/e2e/e2e_suite_test.go
  v2/test/e2e/mpi_job_test.go
Labels: approved, lgtm, size/L

#398 Remove ability to run ranks in launcher
  v2/pkg/controller/mpi_job_controller.go
  v2/pkg/controller/mpi_job_controller_test.go
  v2/test/integration/mpi_job_controller_test.go
Labels: approved, lgtm, size/L

#404 Add alculquicondor as reviewer
  OWNERS
Labels: approved, lgtm, size/XS

#405 Increase E2E wait timeout
  v2/test/e2e/e2e_suite_test.go
Labels: approved, lgtm, size/XS

#406 Increase unit coverage of v2 controller
  v2/pkg/controller/mpi_job_controller.go
  v2/pkg/controller/mpi_job_controller_status.go
  v2/pkg/controller/mpi_job_controller_test.go
Labels: approved, lgtm, size/L

#409 Use fully-qualified label names from common
  v2/go.mod
  v2/go.sum
  v2/pkg/apis/kubeflow/v2beta1/constants.go
  v2/pkg/controller/mpi_job_controller.go
  v2/pkg/controller/mpi_job_controller_test.go
Labels: approved, lgtm, size/L

#411 Add compiled manifest for v2beta1
  deploy/v2beta1/mpi-operator.yaml
Labels: approved, lgtm, size/L

#420 Set OnFailure default restart policy for launcher
  v2/pkg/apis/kubeflow/v2beta1/constants.go
  v2/pkg/apis/kubeflow/v2beta1/default.go
  v2/pkg/apis/kubeflow/v2beta1/default_test.go
  v2/pkg/controller/mpi_job_controller_test.go
Labels: approved, size/XS
