Repository kubeflow/mpi-operator, pull requests merged in 2023-09, with the labels that each got.

#590 Add PITS Global Data Recovery Services as an adopter
  ADOPTERS.md
Labels: approved, size/XS

#589 update volcano scheduler to 1.8.0; ignore vendor
  .gitignore
  Makefile
  go.mod
  go.sum
Labels: approved, lgtm, size/XS

#575 Allow to change registry via a variable
  Makefile
Labels: approved, lgtm, size/S
