Repository kubeflow/mpi-operator, pull requests merged in 2023-04, with the labels that each got.

#540 Implement E2E for integration with scheduler-plugins
  .gitignore
  Makefile
  test/e2e/e2e_suite_test.go
  test/e2e/mpi_job_test.go
Labels: approved, lgtm, size/L

#543 Fix the logic to calculate minResources
  pkg/controller/podgroup.go
Labels: approved, lgtm, size/S

#547 Add written permission to the dep-manifests dir
  Makefile
Labels: approved, lgtm, size/XS

#545 Add versioned labels to images
  Dockerfile
  Makefile
  build/base/Dockerfile
  build/base/intel-builder.Dockerfile
  build/base/intel.Dockerfile
  build/base/openmpi-builder.Dockerfile
  build/base/openmpi.Dockerfile
  examples/v2beta1/pi/Dockerfile
  examples/v2beta1/pi/intel.Dockerfile
  examples/v2beta1/pi/pi.yaml
  test/e2e/e2e_suite_test.go
Labels: approved, lgtm, size/M

#544 Prepare for releasing v0.4.0
  Makefile
  README.md
  RELEASE.md
Labels: approved, lgtm, size/S

#548 Setting Intel MPI architectures separately
  Makefile
Labels: approved, lgtm, size/XS

#551 Fix broken README link
  README.md
Labels: approved, lgtm, size/XS
