Repository kubeflow/mpi-operator, pull requests merged in 2023-01, with the labels that each got.

#489 Adding mpi-operator workflow to release multi-arch docker image
  .github/workflows/mpi-operator-docker-image-publish.yml
Labels: approved, lgtm, size/M

#494 Remove kubectl-delivery
  .github/workflows/codeql.yml
  .github/workflows/golangci-lint.yml
  .github/workflows/main.yml
  Makefile
  cmd/kubectl-delivery/Dockerfile
  cmd/kubectl-delivery/app/options/options.go
  cmd/kubectl-delivery/app/server.go
  cmd/kubectl-delivery/main.go
  go.mod
  go.sum
  pkg/controllers/kubectl_delivery/controller.go
  pkg/controllers/kubectl_delivery/controller_test.go
  pkg/controllers/kubectl_delivery/utils_test.go
  pkg/version/version.go
  v2/test/integration/mpi_job_controller_test.go
Labels: approved, lgtm, size/XXL

#495 Fix documentation
  README.md
Labels: approved, lgtm, size/XS

#497 Upgrade Go version to v1.19
  .github/workflows/codeql.yml
  .github/workflows/golangci-lint.yml
  .github/workflows/main.yml
  CONTRIBUTING.md
  Dockerfile
  Makefile
  go.mod
  pkg/client/clientset/versioned/fake/register.go
  pkg/client/clientset/versioned/scheme/register.go
Labels: approved, lgtm, size/M

#506 Rename Go module name to 'github.com/kubeflow/mpi-operator'
  Makefile
  cmd/mpi-operator/app/options/options.go
  cmd/mpi-operator/app/server.go
  cmd/mpi-operator/main.go
  go.mod
  hack/python-sdk/gen-sdk.sh
  hack/python-sdk/main.go
  hack/update-codegen.sh
  pkg/apis/kubeflow/v2beta1/openapi_generated.go
  pkg/apis/kubeflow/validation/validation.go
  pkg/apis/kubeflow/validation/validation_test.go
  pkg/client/clientset/versioned/clientset.go
  pkg/client/clientset/versioned/fake/clientset_generated.go
  pkg/client/clientset/versioned/fake/register.go
  pkg/client/clientset/versioned/scheme/register.go
  pkg/client/clientset/versioned/typed/kubeflow/v2beta1/fake/fake_kubeflow_client.go
  pkg/client/clientset/versioned/typed/kubeflow/v2beta1/fake/fake_mpijob.go
  pkg/client/clientset/versioned/typed/kubeflow/v2beta1/kubeflow_client.go
  pkg/client/clientset/versioned/typed/kubeflow/v2beta1/mpijob.go
  pkg/client/informers/externalversions/factory.go
  pkg/client/informers/externalversions/generic.go
  pkg/client/informers/externalversions/internalinterfaces/factory_interfaces.go
  pkg/client/informers/externalversions/kubeflow/interface.go
  pkg/client/informers/externalversions/kubeflow/v2beta1/interface.go
  pkg/client/informers/externalversions/kubeflow/v2beta1/mpijob.go
  pkg/client/listers/kubeflow/v2beta1/mpijob.go
  pkg/controller/mpi_job_controller.go
  pkg/controller/mpi_job_controller_status.go
  pkg/controller/mpi_job_controller_test.go
  test/e2e/e2e_suite_test.go
  test/e2e/mpi_job_test.go
  test/integration/main_test.go
  test/integration/mpi_job_controller_test.go
Labels: approved, lgtm, size/L

#512 Add scheduling.volcano.sh to ClusterRole
  manifests/base/cluster-role.yaml
Labels: approved, lgtm, size/XS

#513 Use local copy of RunPolicy by MPI-operator
  pkg/apis/kubeflow/v2beta1/default.go
  pkg/apis/kubeflow/v2beta1/default_test.go
  pkg/apis/kubeflow/v2beta1/openapi_generated.go
  pkg/apis/kubeflow/v2beta1/swagger.json
  pkg/apis/kubeflow/v2beta1/types.go
  pkg/apis/kubeflow/v2beta1/zz_generated.deepcopy.go
  pkg/apis/kubeflow/validation/validation.go
  pkg/apis/kubeflow/validation/validation_test.go
  pkg/controller/mpi_job_controller.go
  pkg/controller/mpi_job_controller_test.go
  sdk/python/v2beta1/README.md
  sdk/python/v2beta1/docs/V2beta1MPIJobSpec.md
  sdk/python/v2beta1/docs/V2beta1RunPolicy.md
  sdk/python/v2beta1/docs/V2beta1SchedulingPolicy.md
  sdk/python/v2beta1/mpijob/__init__.py
  sdk/python/v2beta1/mpijob/models/__init__.py
  sdk/python/v2beta1/mpijob/models/v2beta1_mpi_job_spec.py
  sdk/python/v2beta1/mpijob/models/v2beta1_run_policy.py
  sdk/python/v2beta1/mpijob/models/v2beta1_scheduling_policy.py
  sdk/python/v2beta1/test/test_v2beta1_run_policy.py
  sdk/python/v2beta1/test/test_v2beta1_scheduling_policy.py
  test/integration/mpi_job_controller_test.go
Labels: approved, lgtm, size/L
