Repository kubeflow/mpi-operator, pull requests merged in 2024-04, with the labels that each got.

#632 Promote @tenzen-y to approver
  OWNERS
Labels: approved, size/XS

#637 Upgrade golang and controller-gen
  Dockerfile
  Makefile
  deploy/v2beta1/mpi-operator.yaml
  go.mod
  go.sum
  manifests/base/kubeflow.org_mpijobs.yaml
Labels: approved, lgtm, size/XXL

#635 Replace original pointer methods with ptr libs
  pkg/apis/kubeflow/v2beta1/default.go
  pkg/apis/kubeflow/v2beta1/default_test.go
  pkg/apis/kubeflow/validation/validation_test.go
  pkg/controller/mpi_job_controller.go
  pkg/controller/mpi_job_controller_test.go
  test/e2e/mpi_job_test.go
  test/integration/mpi_job_controller_test.go
Labels: approved, lgtm, size/L

#633 Upgrade K8s dependencies to v1.29
  .github/workflows/golangci-lint.yml
  .github/workflows/main.yml
  Makefile
  README.md
  deploy/v2beta1/mpi-operator.yaml
  go.mod
  go.sum
  hack/update-codegen.sh
  manifests/base/kubeflow.org_mpijobs.yaml
  pkg/apis/kubeflow/v2beta1/swagger.json
  pkg/client/clientset/versioned/doc.go
  pkg/client/informers/externalversions/factory.go
  test/e2e/e2e_suite_test.go
  test/integration/mpi_job_controller_test.go
Labels: approved, lgtm, size/XXL

#634 Introduce resource multiplication
  pkg/controller/podgroup.go
  pkg/controller/podgroup_test.go
Labels: approved, lgtm, size/S

#631 Prepare for release 0.5.0
  Makefile
  README.md
  RELEASE.md
Labels: approved, lgtm, size/S

#638 Update image tag with 0.5
  deploy/v2beta1/mpi-operator.yaml
  manifests/overlays/kubeflow/kustomization.yaml
  manifests/overlays/standalone/kustomization.yaml
Labels: approved, lgtm, size/XS
