Repository kubeflow/mpi-operator, pull requests merged in 2024-02, with the labels that each got.

#623 update auto gen file year to verify generate
  pkg/apis/kubeflow/v2beta1/zz_generated.deepcopy.go
  pkg/client/applyconfiguration/internal/internal.go
  pkg/client/applyconfiguration/kubeflow/v2beta1/jobcondition.go
  pkg/client/applyconfiguration/kubeflow/v2beta1/jobstatus.go
  pkg/client/applyconfiguration/kubeflow/v2beta1/mpijob.go
  pkg/client/applyconfiguration/kubeflow/v2beta1/mpijobspec.go
  pkg/client/applyconfiguration/kubeflow/v2beta1/replicaspec.go
  pkg/client/applyconfiguration/kubeflow/v2beta1/replicastatus.go
  pkg/client/applyconfiguration/kubeflow/v2beta1/runpolicy.go
  pkg/client/applyconfiguration/kubeflow/v2beta1/schedulingpolicy.go
  pkg/client/applyconfiguration/utils.go
  pkg/client/clientset/versioned/clientset.go
  pkg/client/clientset/versioned/doc.go
  pkg/client/clientset/versioned/fake/clientset_generated.go
  pkg/client/clientset/versioned/fake/doc.go
  pkg/client/clientset/versioned/fake/register.go
  pkg/client/clientset/versioned/scheme/doc.go
  pkg/client/clientset/versioned/scheme/register.go
  pkg/client/clientset/versioned/typed/kubeflow/v2beta1/doc.go
  pkg/client/clientset/versioned/typed/kubeflow/v2beta1/fake/doc.go
  pkg/client/clientset/versioned/typed/kubeflow/v2beta1/fake/fake_kubeflow_client.go
  pkg/client/clientset/versioned/typed/kubeflow/v2beta1/fake/fake_mpijob.go
  pkg/client/clientset/versioned/typed/kubeflow/v2beta1/generated_expansion.go
  pkg/client/clientset/versioned/typed/kubeflow/v2beta1/kubeflow_client.go
  pkg/client/clientset/versioned/typed/kubeflow/v2beta1/mpijob.go
  pkg/client/informers/externalversions/factory.go
  pkg/client/informers/externalversions/generic.go
  pkg/client/informers/externalversions/internalinterfaces/factory_interfaces.go
  pkg/client/informers/externalversions/kubeflow/interface.go
  pkg/client/informers/externalversions/kubeflow/v2beta1/interface.go
  pkg/client/informers/externalversions/kubeflow/v2beta1/mpijob.go
  pkg/client/listers/kubeflow/v2beta1/expansion_generated.go
  pkg/client/listers/kubeflow/v2beta1/mpijob.go
Labels: approved, lgtm, size/M

#624 adding Mac .DS_Store to gitignore
  .gitignore
Labels: approved, lgtm, size/XS

#619 Fails mpi-operator early if access to list or watch objects is denied
  pkg/controller/mpi_job_controller.go
Labels: approved, lgtm, size/S

#622 Fix: add ns filter to podLister
  pkg/controller/mpi_job_controller.go
Labels: approved, lgtm, size/XS

#612 run worker process in launcher pod
  deploy/v2beta1/mpi-operator.yaml
  go.mod
  go.sum
  manifests/base/kubeflow.org_mpijobs.yaml
  pkg/apis/kubeflow/v2beta1/swagger.json
  pkg/apis/kubeflow/v2beta1/types.go
  pkg/apis/kubeflow/v2beta1/zz_generated.deepcopy.go
  pkg/client/applyconfiguration/kubeflow/v2beta1/mpijobspec.go
  pkg/controller/mpi_job_controller.go
  pkg/controller/mpi_job_controller_test.go
  sdk/python/v2beta1/docs/V2beta1MPIJobSpec.md
  sdk/python/v2beta1/mpijob/models/v2beta1_mpi_job_spec.py
Labels: approved, lgtm, size/L

#627 Deprecated pointer, use ptr instead
  pkg/controller/mpi_job_controller.go
  pkg/controller/mpi_job_controller_test.go
  pkg/controller/podgroup.go
  pkg/controller/podgroup_test.go
  test/e2e/mpi_job_test.go
  test/integration/mpi_job_controller_test.go
Labels: approved, lgtm, size/L
