Repository kubeflow/mpi-operator, pull requests merged in 2024-10, with the labels that each got.

#653 Upgrade the scheduler-plugins to v0.29.8
  go.mod
  go.sum
  test/e2e/e2e_suite_test.go
Labels: approved, lgtm, size/M

#650 Introduce ManagedBy field in RunPolicy
  deploy/v2beta1/mpi-operator.yaml
  manifests/base/kubeflow.org_mpijobs.yaml
  pkg/apis/kubeflow/v2beta1/swagger.json
  pkg/apis/kubeflow/v2beta1/types.go
  pkg/apis/kubeflow/v2beta1/zz_generated.deepcopy.go
  pkg/apis/kubeflow/validation/validation.go
  pkg/apis/kubeflow/validation/validation_test.go
  pkg/client/applyconfiguration/kubeflow/v2beta1/runpolicy.go
  pkg/controller/mpi_job_controller.go
  pkg/controller/mpi_job_controller_test.go
  sdk/python/v2beta1/docs/V2beta1RunPolicy.md
  sdk/python/v2beta1/mpijob/models/v2beta1_run_policy.py
  test/e2e/mpi_job_test.go
  test/integration/main_test.go
  test/integration/mpi_job_controller_test.go
  test/util/constants.go
Labels: approved, lgtm, size/L, ok-to-test

#656 Adjust the comment for managedBy
  deploy/v2beta1/mpi-operator.yaml
  manifests/base/kubeflow.org_mpijobs.yaml
  pkg/apis/kubeflow/v2beta1/swagger.json
  pkg/apis/kubeflow/v2beta1/types.go
  sdk/python/v2beta1/docs/V2beta1RunPolicy.md
  sdk/python/v2beta1/mpijob/models/v2beta1_run_policy.py
Labels: approved, lgtm, size/XS

#663 Obviously specify the supported platforms in Makefile
  .github/workflows/main.yml
  Makefile
Labels: approved, lgtm, size/S

#661 Introduce debian bookworm
  build/base/Dockerfile
  build/base/intel-builder.Dockerfile
  build/base/mpich-builder.Dockerfile
  build/base/openmpi-builder.Dockerfile
  examples/v2beta1/pi/pi.cc
Labels: approved, lgtm, size/S

#659 Upgrade volcano version to v1.10.0
  go.mod
  go.sum
  test/e2e/e2e_suite_test.go
Labels: approved, lgtm, size/XS

#664 Bump to k8s 1.31
  .github/workflows/golangci-lint.yml
  .github/workflows/main.yml
  Dockerfile
  Makefile
  deploy/v2beta1/mpi-operator.yaml
  go.mod
  go.sum
  manifests/base/kubeflow.org_mpijobs.yaml
  pkg/apis/kubeflow/v2beta1/swagger.json
  pkg/apis/kubeflow/v2beta1/zz_generated.openapi.go
  pkg/client/applyconfiguration/kubeflow/v2beta1/jobcondition.go
  pkg/client/applyconfiguration/kubeflow/v2beta1/jobstatus.go
  pkg/client/applyconfiguration/kubeflow/v2beta1/mpijob.go
  pkg/client/applyconfiguration/kubeflow/v2beta1/mpijobspec.go
  pkg/client/applyconfiguration/kubeflow/v2beta1/replicaspec.go
  pkg/client/applyconfiguration/kubeflow/v2beta1/replicastatus.go
  pkg/client/applyconfiguration/kubeflow/v2beta1/runpolicy.go
  pkg/client/applyconfiguration/kubeflow/v2beta1/schedulingpolicy.go
  pkg/client/applyconfiguration/utils.go
  pkg/client/clientset/versioned/fake/clientset_generated.go
  pkg/client/clientset/versioned/typed/kubeflow/v2beta1/fake/fake_mpijob.go
  pkg/client/clientset/versioned/typed/kubeflow/v2beta1/mpijob.go
  pkg/client/informers/externalversions/factory.go
  pkg/client/listers/kubeflow/v2beta1/mpijob.go
  pkg/controller/mpi_job_controller.go
  sdk/python/v2beta1/README.md
  sdk/python/v2beta1/docs/V1FieldSelectorRequirement.md
  sdk/python/v2beta1/mpijob/__init__.py
  sdk/python/v2beta1/mpijob/models/__init__.py
  sdk/python/v2beta1/mpijob/models/v1_field_selector_requirement.py
  sdk/python/v2beta1/test/test_v1_field_selector_requirement.py
  test/e2e/e2e_suite_test.go
Labels: approved, lgtm, size/XXL

#665 Prepare v0.6.0 release
  Makefile
  README.md
  RELEASE.md
Labels: approved, lgtm, size/S

#667 Reuse the core kubernetes API reason for the BackoffLimitExceeded
  pkg/controller/mpi_job_controller.go
  pkg/controller/mpi_job_controller_test.go
Labels: approved, lgtm, size/S

#666 Fix the 'printf: non-constant format string in call to fmt.Errorf (govet)' lint errors
  .github/workflows/golangci-lint.yml
  Makefile
  pkg/controller/mpi_job_controller.go
Labels: approved, lgtm, size/M

#668 Update image tag with release-0.6
  deploy/v2beta1/mpi-operator.yaml
  manifests/overlays/kubeflow/kustomization.yaml
  manifests/overlays/standalone/kustomization.yaml
Labels: approved, lgtm, size/XS
