Repository kubeflow/mpi-operator, pull requests merged in 2025-01, with the labels that each got.

#676 Fix E2E Intel MPI integ tests
  build/base/intel-builder.Dockerfile
  build/base/intel.Dockerfile
  pkg/apis/kubeflow/v2beta1/zz_generated.deepcopy.go
  pkg/apis/kubeflow/v2beta1/zz_generated.defaults.go
  pkg/client/applyconfiguration/internal/internal.go
  pkg/client/applyconfiguration/kubeflow/v2beta1/jobcondition.go
  pkg/client/applyconfiguration/kubeflow/v2beta1/jobstatus.go
  pkg/client/applyconfiguration/kubeflow/v2beta1/mpijob.go
  pkg/client/applyconfiguration/kubeflow/v2beta1/mpijobspec.go
  pkg/client/applyconfiguration/kubeflow/v2beta1/replicaspec.go
  pkg/client/applyconfiguration/kubeflow/v2beta1/replicastatus.go
  pkg/client/applyconfiguration/kubeflow/v2beta1/runpolicy.go
  pkg/client/applyconfiguration/kubeflow/v2beta1/schedulingpolicy.go
  pkg/client/applyconfiguration/utils.go
  pkg/client/clientset/versioned/clientset.go
  pkg/client/clientset/versioned/fake/clientset_generated.go
  pkg/client/clientset/versioned/fake/doc.go
  pkg/client/clientset/versioned/fake/register.go
  pkg/client/clientset/versioned/scheme/doc.go
  pkg/client/clientset/versioned/scheme/register.go
  pkg/client/clientset/versioned/typed/kubeflow/v2beta1/doc.go
  pkg/client/clientset/versioned/typed/kubeflow/v2beta1/fake/doc.go
  pkg/client/clientset/versioned/typed/kubeflow/v2beta1/fake/fake_kubeflow_client.go
  pkg/client/clientset/versioned/typed/kubeflow/v2beta1/fake/fake_mpijob.go
  pkg/client/clientset/versioned/typed/kubeflow/v2beta1/generated_expansion.go
  pkg/client/clientset/versioned/typed/kubeflow/v2beta1/kubeflow_client.go
  pkg/client/clientset/versioned/typed/kubeflow/v2beta1/mpijob.go
  pkg/client/informers/externalversions/factory.go
  pkg/client/informers/externalversions/generic.go
  pkg/client/informers/externalversions/internalinterfaces/factory_interfaces.go
  pkg/client/informers/externalversions/kubeflow/interface.go
  pkg/client/informers/externalversions/kubeflow/v2beta1/interface.go
  pkg/client/informers/externalversions/kubeflow/v2beta1/mpijob.go
  pkg/client/listers/kubeflow/v2beta1/expansion_generated.go
  pkg/client/listers/kubeflow/v2beta1/mpijob.go
Labels: approved, lgtm, size/M

#674 Expose job controller's workqueue rate limiting configs
  ADOPTERS.md
  cmd/mpi-operator/app/options/options.go
  cmd/mpi-operator/app/server.go
  pkg/controller/mpi_job_controller.go
  pkg/controller/mpi_job_controller_test.go
  test/integration/mpi_job_controller_test.go
Labels: approved, lgtm, size/M

#673 chore: bump golang.org/x/crypto from v0.26.0 to v0.31.0
  go.mod
  go.sum
Labels: approved, size/M

#669 Fix crash in podgroup when runLauncherAsWorker is true
  pkg/controller/podgroup.go
  pkg/controller/podgroup_test.go
Labels: approved, lgtm, size/L
