Repository kubeflow/mpi-operator, pull requests merged in 2025-04, with the labels that each got.

#692 Trust the Intel OneAPI PGP key until it satisfies new APT PGP requirments
  build/base/intel-builder.Dockerfile
  build/base/intel.Dockerfile
Labels: approved, lgtm, size/XS

#693 Remove alculquicondor from OWNERS
  OWNERS
Labels: approved, size/XS

#695 Upgrade Go version to 1.24
  .github/workflows/golangci-lint.yml
  Dockerfile
  Makefile
  go.mod
Labels: lgtm, size/S

#690 Fix missing ReplicaIndexLabel when using RunLauncherAsWorker
  pkg/controller/mpi_job_controller.go
  pkg/controller/mpi_job_controller_test.go
Labels: approved, lgtm, size/S
